apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ro14mxy20-go 
  janus-idp.io/tekton: ro14mxy20-go
  backstage.io/kubernetes-id: ro14mxy20-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ro14mxy20-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml