apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ro14mxy20-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ro14mxy20-go 
  name: ro14mxy20-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ro14mxy20-go 
